from .api_nodes import (
    NODE_CLASS_MAPPINGS as API_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as API_NODE_DISPLAY_NAME_MAPPINGS,
)
from .tdxh_node_comfyui import (
    NODE_CLASS_MAPPINGS as TDXH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TDXH_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **TDXH_NODE_CLASS_MAPPINGS,
    **API_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TDXH_NODE_DISPLAY_NAME_MAPPINGS,
    **API_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
