from .deepseek_nodes import (
    NODE_CLASS_MAPPINGS as DEEPSEEK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .kimi_nodes import (
    NODE_CLASS_MAPPINGS as KIMI_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KIMI_NODE_DISPLAY_NAME_MAPPINGS,
)
from .multi_platform_chat_node import (
    NODE_CLASS_MAPPINGS as MULTI_PLATFORM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_PLATFORM_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **DEEPSEEK_NODE_CLASS_MAPPINGS,
    **KIMI_NODE_CLASS_MAPPINGS,
    **MULTI_PLATFORM_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS,
    **KIMI_NODE_DISPLAY_NAME_MAPPINGS,
    **MULTI_PLATFORM_NODE_DISPLAY_NAME_MAPPINGS,
}
