from .providers import (
    NODE_CLASS_MAPPINGS as PROVIDER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROVIDER_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **PROVIDER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROVIDER_NODE_DISPLAY_NAME_MAPPINGS,
}
